//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationToPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationToPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint &amp; Word files | *.ppt; *.pptx; *.doc; *.docx.
        /// </summary>
        internal static string AddFilesFilter {
            get {
                return ResourceManager.GetString("AddFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select presentations to convert....
        /// </summary>
        internal static string AddFilesTitle {
            get {
                return ResourceManager.GetString("AddFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder: 
        ///{0}
        ///could not be accessed because access to the specified location is denied. The file of folder may be in use by another program..
        /// </summary>
        internal static string MsgDirCreationFailed_Access {
            get {
                return ResourceManager.GetString("MsgDirCreationFailed_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory is invalid:
        ///{0}
        ///You can select an existing folder by clicking Browse..
        /// </summary>
        internal static string MsgDirCreationFailed_Invalid {
            get {
                return ResourceManager.GetString("MsgDirCreationFailed_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create output folder: 
        ///{0}
        ///The drive may be out of space..
        /// </summary>
        internal static string MsgDirCreationFailed_IO {
            get {
                return ResourceManager.GetString("MsgDirCreationFailed_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the output folder is too long: 
        ///{0}
        ///Choose a shorter path, e.g. your Desktop..
        /// </summary>
        internal static string MsgDirCreationFailed_Path {
            get {
                return ResourceManager.GetString("MsgDirCreationFailed_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured. Restart the program and try again..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
